name: order-hub-v1
image:
  repository: miguelarmasabt/order-hub
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8018
  nodePort: 30018
replicas: 1

configMaps:
  CONFIG_SERVER_DOMAIN: "config-server-v1:8888"
  MENU_V1_DOMAIN: "menu-v1:8012"
  MENU_V2_DOMAIN: "menu-v2:8016"
  TABLE_PLACEMENT_DOMAIN: "table-placement-v1:8013"
  INVOICE_DOMAIN: "invoice-v1:8014"
  MENU_REPOSITORY_SELECTOR: "com.demo.poc.entrypoint.menu.repository.MenuV1Repository"
  JAVA_OPTS: "-Xms256M -Xmx256M"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8018
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8018
  initialDelaySeconds: 60
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8018
  dependencies: config-server-v1;redis-server
  volumes: none