package com.demo.poc.commons.core.tracing.enums;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.function.Supplier;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum AutoGeneratedParam {

  TIMESTAMP("timestamp", Util.getLocalDate);

  private final String key;
  private final Supplier<String> generator;

  @NoArgsConstructor(access = AccessLevel.PRIVATE)
  public static final class Util {

    public static final String DEFAULT_DATE_PATTERN = "yyyyMMddHHmmssSSS";

    public static final Supplier<String> getLocalDate = () ->
        LocalDateTime.now().format(DateTimeFormatter.ofPattern(DEFAULT_DATE_PATTERN));

  }
}
