---
# Source: generic-server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-v7
  labels:
    app: redis-v7
spec:
  type: NodePort
  selector:
    app: redis-v7
  ipFamilies:
    - IPv4
  ports:
    - name: redis-v7
      port: 6379
      nodePort: 30379
---
# Source: generic-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-v7
  labels:
    app: redis-v7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-v7
  template:
    metadata:
      labels:
        app: redis-v7
    spec:
      containers:
        - name: redis-v7
          image: "redis:7"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          env: