---
# Source: generic-server-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: custom-redis
  labels:
    app: custom-redis
spec:
  type: NodePort
  selector:
    app: custom-redis
  ipFamilies:
    - IPv4
  ports:
    - name: custom-redis
      port: 6379
      nodePort: 30379
---
# Source: generic-server-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-redis
  labels:
    app: custom-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-redis
  template:
    metadata:
      labels:
        app: custom-redis
    spec:
      containers:
        - name: custom-redis
          image: "redis:7"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          env: