server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ubigeo-v1

  data:
    redis:
      host: ${REDIS_DOMAIN}
      port: 6379
      timeout: 2500
  cache:
    type: redis #enable cache

configuration:
  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  filePaths:
    departments: ubigeo/departments.json
    provinces: ubigeo/provinces.json
    districts: ubigeo/districts.json

  cache:
    departments:
      time-to-live: MINUTE
      key-prefix: demo.departments
    provinces:
      time-to-live: MINUTE
      key-prefix: demo.provinces
    districts:
      time-to-live: MINUTE
      key-prefix: demo.districts

# actuator endpoints
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always
      probes: #livess & readiness probe
        enabled: true