package com.demo.poc.commons.core.properties.restclient;

import java.util.Map;

import com.demo.poc.commons.core.tracing.enums.AutoGeneratedParam;
import com.demo.poc.commons.core.tracing.enums.TraceParam;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class HeaderTemplate {

  private Map<String, String> provided;
  private Map<String, String> forwarded;
  private Map<String, AutoGeneratedParam> autoGenerated;
  private Map<String, TraceParam> tracing;

}
